"use client" // Needs browser APIs (camera, mic, MediaRecorder) so must be a Client Component

import { useState, useRef, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"

// Questions and config are loaded from sessionStorage
// They were generated by Claude on the setup page
type Question = { type: string; text: string }

type SessionConfig = {
    role: string
    level: string
    language: string
    company: string
    questions: Question[]
}

// Fallback questions if user navigates directly to /session without setup
const DEFAULT_QUESTIONS: Question[] = [
    { type: "Behavioral", text: "Tell me about a time you had to deal with a difficult teammate." },
    { type: "Behavioral", text: "Describe a project you're most proud of and your role in it." },
    { type: "Technical", text: "How would you design a URL shortener like bit.ly?" },
    { type: "Situational", text: "You have two deadlines clashing. How do you handle it?" },
]

// Maps verdict string to Tailwind color classes for the badge
const verdictColors: Record<string, string> = {
    strong: "bg-green-100 text-green-800",
    good: "bg-blue-100 text-blue-800",
    needs_work: "bg-yellow-100 text-yellow-800",
    poor: "bg-red-100 text-red-800",
}

// List of filler words to detect — can expand this list anytime
const FILLER_WORDS = ["um", "uh", "like", "so", "you know", "basically", "literally", "right", "okay", "actually"]

// Counts how many filler words appear in the transcript
function countFillers(text: string): Record<string, number> {
    const lower = text.toLowerCase()
    const counts: Record<string, number> = {}
    FILLER_WORDS.forEach((word) => {
        const matches = lower.match(new RegExp(`\\b${word}\\b`, "g"))
        if (matches && matches.length > 0) counts[word] = matches.length
    })
    return counts
}

// Wraps filler words in a highlighted span so they stand out in the transcript
function highlightFillers(text: string): string {
    let result = text
    FILLER_WORDS.forEach((word) => {
        const regex = new RegExp(`\\b(${word})\\b`, "gi")
        result = result.replace(regex, `<mark class="bg-yellow-200 text-yellow-900 rounded px-0.5">$1</mark>`)
    })
    return result
}

// Stores the full result for one completed question
type QuestionResult = {
    question: string
    type: string
    transcript: string
    analysis: Analysis
    fillerCount: number
}

// TypeScript type for the analysis response from Claude
type Analysis = {
    overall_score: number
    verdict: string
    dimensions: {
        relevance: { score: number; feedback: string }
        star_method: { score: number; feedback: string }
        specificity: { score: number; feedback: string }
        conciseness: { score: number; feedback: string }
    }
    top_strength: string
    top_improvement: string
}

export default function SessionPage() {
    const [currentQ, setCurrentQ] = useState(0)
    const [isRecording, setIsRecording] = useState(false)
    const [cameraReady, setCameraReady] = useState(false)
    const [error, setError] = useState<string | null>(null)
    const [transcript, setTranscript] = useState("")
    const [isTranscribing, setIsTranscribing] = useState(false)
    const [isAnalyzing, setIsAnalyzing] = useState(false)
    const [analysis, setAnalysis] = useState<Analysis | null>(null)
    const [language, setLanguage] = useState("en")
    const [fillerCounts, setFillerCounts] = useState<Record<string, number>>({})
    const [results, setResults] = useState<QuestionResult[]>([])

    // Dynamic questions loaded from sessionStorage (generated by Claude on setup page)
    const [questions, setQuestions] = useState<Question[]>(DEFAULT_QUESTIONS)
    // Session config holds role, level, language, company for context-aware feedback
    const [sessionConfig, setSessionConfig] = useState<SessionConfig | null>(null)

    // useRef for DOM elements and mutable values that shouldn't trigger re-renders
    const videoRef = useRef<HTMLVideoElement>(null)
    const streamRef = useRef<MediaStream | null>(null)
    const mediaRecorderRef = useRef<MediaRecorder | null>(null)
    const chunksRef = useRef<Blob[]>([])

    // Current question based on index
    const question = questions[currentQ]
    // Guard against currentQ going out of bounds
    if (!question) return null

    // Load session config from sessionStorage on mount
    // This was saved by the setup page after Claude generated the questions
    useEffect(() => {
        const stored = sessionStorage.getItem("sessionConfig")
        if (stored) {
            const config = JSON.parse(stored) as SessionConfig
            setSessionConfig(config)
            setQuestions(config.questions)
            setLanguage(config.language || "en")
        }
    }, [])

    // Start camera on mount, clean up on unmount
    useEffect(() => {
        startCamera()
        return () => stopCamera()
    }, [])

    async function startCamera() {
        try {
            const stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true })
            streamRef.current = stream
            if (videoRef.current) videoRef.current.srcObject = stream
            setCameraReady(true)
        } catch {
            setError("Could not access camera or microphone. Please allow permissions and refresh.")
        }
    }

    function stopCamera() {
        streamRef.current?.getTracks().forEach((track) => track.stop())
    }

    async function startRecording() {
        if (!streamRef.current) return
        chunksRef.current = []
        setFillerCounts({})

        const recorder = new MediaRecorder(streamRef.current)
        mediaRecorderRef.current = recorder

        recorder.ondataavailable = (e) => {
            if (e.data.size > 0) chunksRef.current.push(e.data)
        }

        // When recording stops, send audio to Whisper for transcription
        recorder.onstop = async () => {
            const blob = new Blob(chunksRef.current, { type: "audio/webm" })
            await sendToTranscribe(blob)
        }

        recorder.start()
        setIsRecording(true)
        setTranscript("")
        setAnalysis(null)
    }

    function stopRecording() {
        mediaRecorderRef.current?.stop()
        setIsRecording(false)
    }

    async function sendToTranscribe(blob: Blob) {
        setIsTranscribing(true)
        try {
            const formData = new FormData()
            formData.append("audio", blob, "recording.webm")

            const response = await fetch("/api/transcribe", { method: "POST", body: formData })
            const data = await response.json()
            setTranscript(data.transcript)
            setFillerCounts(countFillers(data.transcript))
            setLanguage(data.language || "en")

            // Automatically analyze once transcript is ready
            await analyzeAnswer(data.transcript, data.language || "en")
        } catch {
            setTranscript("Transcription failed. Please try again.")
        } finally {
            setIsTranscribing(false)
        }
    }

    async function analyzeAnswer(transcriptText: string, lang: string) {
        setIsAnalyzing(true)
        try {
            const response = await fetch("/api/analyze", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    question: question.text,
                    transcript: transcriptText,
                    language: lang,
                    // Pass role + level so Claude gives role-specific feedback
                    role: sessionConfig?.role || "Software Developer",
                    level: sessionConfig?.level || "mid",
                }),
            })
            const data = await response.json()
            setAnalysis(data)
        } catch {
            console.error("Analysis failed")
        } finally {
            setIsAnalyzing(false)
        }
    }

    function handleNextQuestion() {
        // Save current result before moving to next question
        if (analysis) {
            setResults(prev => [...prev, {
                question: question.text,
                type: question.type,
                transcript,
                analysis,
                fillerCount: Object.values(fillerCounts).reduce((a, b) => a + b, 0)
            }])
        }
        setIsRecording(false)
        setTranscript("")
        setAnalysis(null)
        setFillerCounts({})
        setCurrentQ(currentQ + 1)
    }

    function handleFinish() {
        const finalResults = analysis ? [...results, {
            question: question.text,
            type: question.type,
            transcript,
            analysis,
            fillerCount: Object.values(fillerCounts).reduce((a, b) => a + b, 0)
        }] : results

        // Save to both storages — session for summary page, local for history
        sessionStorage.setItem("interviewResults", JSON.stringify(finalResults))
        localStorage.setItem("lastSession", JSON.stringify(finalResults))
        window.location.href = "/summary"
    }

    return (
        <main className="min-h-screen flex flex-col items-center justify-center px-4 py-16 gap-8 max-w-3xl mx-auto">

            {/* Header — shows role/level if available, otherwise generic title */}
            <div className="w-full flex items-center justify-between">
                <div>
                    <h1 className="text-2xl font-bold">Interview Session</h1>
                    {sessionConfig && (
                        <p className="text-xs text-muted-foreground mt-0.5">
                            {sessionConfig.role} · {sessionConfig.level}
                            {sessionConfig.company && ` · ${sessionConfig.company}`}
                        </p>
                    )}
                </div>
                <Badge variant="outline">{currentQ + 1} / {questions.length}</Badge>
            </div>

            {/* Question card */}
            <Card className="w-full">
                <CardHeader>
                    <Badge className="w-fit mb-2">{question.type}</Badge>
                    <CardTitle className="text-xl leading-relaxed" dir="auto">
                        {question.text}
                    </CardTitle>
                </CardHeader>
                <CardContent className="flex flex-col gap-4">

                    {/* Camera preview — mirrored so it feels like a mirror */}
                    <div className="w-full aspect-video bg-muted rounded-lg overflow-hidden relative">
                        <video ref={videoRef} autoPlay muted playsInline className="w-full h-full object-cover scale-x-[-1]" />
                        {!cameraReady && !error && (
                            <div className="absolute inset-0 flex items-center justify-center">
                                <p className="text-muted-foreground text-sm">Starting camera...</p>
                            </div>
                        )}
                        {error && (
                            <div className="absolute inset-0 flex items-center justify-center px-4">
                                <p className="text-destructive text-sm text-center">{error}</p>
                            </div>
                        )}
                        {/* Recording indicator */}
                        {isRecording && (
                            <div className="absolute top-3 left-3 flex items-center gap-2">
                                <div className="w-2 h-2 rounded-full bg-red-500 animate-pulse" />
                                <span className="text-xs text-white font-medium">REC</span>
                            </div>
                        )}
                    </div>

                    <div className="flex gap-3 justify-center">
                        <Button
                            size="lg"
                            variant={isRecording ? "destructive" : "default"}
                            onClick={isRecording ? stopRecording : startRecording}
                            disabled={!cameraReady || isTranscribing || isAnalyzing}
                            className={`px-8 transition-all duration-200 ${isRecording ? "ring-4 ring-red-300 ring-offset-2 scale-105" : "hover:scale-105"
                                }`}
                        >
                            {isRecording ? "Stop Recording" : "Start Recording"}
                        </Button>

                        {/* Next on all questions except last, Finish on last */}
                        {currentQ < questions.length - 1 ? (
                            <Button
                                size="lg"
                                variant="outline"
                                onClick={handleNextQuestion}
                                disabled={isRecording || !analysis}
                                className="hover:scale-105 transition-all duration-200"
                            >
                                Next Question
                            </Button>
                        ) : (
                            <Button
                                size="lg"
                                variant="outline"
                                onClick={handleFinish}
                                disabled={isRecording || !analysis}
                                className="hover:scale-105 transition-all duration-200"
                            >
                                Finish Session
                            </Button>
                        )}
                    </div>
                </CardContent>
            </Card>

            {/* Transcript card */}
            <Card className="w-full">
                <CardHeader className="flex flex-row items-center justify-between">
                    <CardTitle className="text-base">Transcript</CardTitle>
                    {Object.keys(fillerCounts).length > 0 && (
                        <span className="text-xs px-2 py-1 rounded-full bg-yellow-100 text-yellow-800 font-medium">
                            {Object.values(fillerCounts).reduce((a, b) => a + b, 0)} filler words
                        </span>
                    )}
                </CardHeader>
                <CardContent className="flex flex-col gap-3">
                    {isTranscribing ? (
                        <p className="text-muted-foreground text-sm animate-pulse">Transcribing your answer...</p>
                    ) : transcript ? (
                        <>
                            {/* dangerouslySetInnerHTML renders highlight tags as real HTML */}
                            <p
                                className="text-sm leading-relaxed"
                                dir="auto"
                                dangerouslySetInnerHTML={{ __html: highlightFillers(transcript) }}
                            />
                            {Object.keys(fillerCounts).length > 0 && (
                                <div className="flex flex-wrap gap-2 pt-1 border-t">
                                    {Object.entries(fillerCounts).map(([word, count]) => (
                                        <span key={word} className="text-xs bg-yellow-50 text-yellow-800 border border-yellow-200 rounded-full px-2 py-0.5">
                                            "{word}" × {count}
                                        </span>
                                    ))}
                                </div>
                            )}
                        </>
                    ) : (
                        <p className="text-muted-foreground text-sm">
                            {isRecording ? "Recording... press Stop when done." : "Press Start Recording to begin."}
                        </p>
                    )}
                </CardContent>
            </Card>

            {/* Loading state while Claude analyzes */}
            {isAnalyzing && (
                <Card className="w-full animate-in slide-in-from-bottom-4 duration-300">
                    <CardContent className="pt-6">
                        <p className="text-muted-foreground text-sm animate-pulse text-center">Analyzing your answer...</p>
                    </CardContent>
                </Card>
            )}

            {/* Feedback card — only renders when analysis is ready */}
            {analysis && (
                <Card className="w-full animate-in slide-in-from-bottom-4 duration-500">
                    <CardHeader className="flex flex-row items-center justify-between">
                        <CardTitle className="text-base">Feedback</CardTitle>
                        <span className={`text-xs font-medium px-2 py-1 rounded-full ${verdictColors[analysis.verdict]}`}>
                            {analysis.verdict.replace("_", " ")} · {analysis.overall_score}/10
                        </span>
                    </CardHeader>
                    <CardContent className="flex flex-col gap-4">
                        {Object.entries(analysis.dimensions).map(([key, val]) => (
                            <div key={key}>
                                <div className="flex justify-between text-sm mb-1">
                                    <span className="capitalize text-muted-foreground">{key.replace("_", " ")}</span>
                                    <span className="font-medium">{val.score}/10</span>
                                </div>
                                {/* Score is 0-10, Progress expects 0-100 */}
                                <Progress value={val.score * 10} className="h-1.5 mb-1" />
                                <p className="text-xs text-muted-foreground">{val.feedback}</p>
                            </div>
                        ))}
                        <div className="border-t pt-4 flex flex-col gap-2">
                            <div className="text-sm">
                                <span className="font-medium text-green-700">Strength: </span>
                                <span className="text-muted-foreground" dir="auto">
                                    {analysis.top_strength}
                                </span>
                            </div>
                            <div className="text-sm">
                                <span className="font-medium text-yellow-700">Improve: </span>
                                <span className="text-muted-foreground" dir="auto">
                                    {analysis.top_improvement}
                                </span>
                            </div>
                        </div>
                    </CardContent>
                </Card>
            )}

        </main>
    )
}